### ISSUE TITLE
What's cf?

### ISSUE THREAD

**Issue by bradleygibson** [nrc/r4cppp#54]
At the end of Chapter 5 Borrowing (emphasis mine):

> These have the syntax &'a T (***cf*** &T).

What's cf?  The next sentence makes sense to me, so I guess I'm just being thrown by a contraction or abbreviation that is escaping me?

*P.S. Thank you* ***so much*** *for this!  As an experienced C++ programmer, this is exactly the perspective for an intro to Rust I've been looking for.*

**Comment by nrc** [comment]
That should be "c.f.", an abbreviation for "contrast with".

I'm glad you like the docs, but beware that they are a bit out of date in places - I haven't had the time to maintain this or continue writing, which makes me a bit sad.

**Comment by bradleygibson** [comment]
You're still saving me (and probably others) lots of time with such a great focused intro to Rust.
I'll make a PR for you and feed you back the (very minor) issues I've found, so at least the doc will get a little love. ;)

If I don't know the answer, I'll just open another issue here, and you can let me know what to put into the PR.  :)
