### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by Jake-Shadle** [nrc/r4cppp#67]
I would like to write a chapter on Rust's error handling and comparing and contrasting it against both integer/custom type error handling and exceptions in C++.

I just wanted to check to see if this would be worthwhile work before I started going too deep.

**Comment by koutheir** [comment]
Excellent idea! I think.

**Comment by nrc** [comment]
@Jake-Shadle please do! That sounds like a great addition.

**Comment by Jake-Shadle** [comment]
Cool, glad to hear that, will start working on that then. 🙂
